=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Net::Sms::TextMagicClient::Object::Chat;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Net::Sms::TextMagicClient::Object::Contact;
use Net::Sms::TextMagicClient::Object::Country;
use Net::Sms::TextMagicClient::Object::Tag;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'Chat',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
        datatype => 'int',
        base_name => 'id',
        description => 'Chat ID.',
        format => '',
        read_only => '',
            },
    'original_id' => {
        datatype => 'int',
        base_name => 'originalId',
        description => '',
        format => '',
        read_only => '',
            },
    'phone' => {
        datatype => 'string',
        base_name => 'phone',
        description => 'Chat partner&#39;s phone number.',
        format => '',
        read_only => '',
            },
    'contact' => {
        datatype => 'Contact',
        base_name => 'contact',
        description => '',
        format => '',
        read_only => '',
            },
    'unsubscribed_contact_id' => {
        datatype => 'int',
        base_name => 'unsubscribedContactId',
        description => 'If this field has a value, it means that the chat phone number has been unsubscribed from you and this value is an ID of an Unsubscribed contact entity. See [Get all unsubscribed contacts](https://docs.textmagic.com/#operation/getUnsubscribers).',
        format => '',
        read_only => '',
            },
    'unread' => {
        datatype => 'int',
        base_name => 'unread',
        description => 'Total unread incoming messages.',
        format => '',
        read_only => '',
            },
    'updated_at' => {
        datatype => 'DATE_TIME',
        base_name => 'updatedAt',
        description => 'Time when the last incoming message arrived at this chat.',
        format => '',
        read_only => '',
            },
    'status' => {
        datatype => 'string',
        base_name => 'status',
        description => 'Chat status:   * **a** - Active;   * **c** - Closed;   * **d** - Deleted. ',
        format => '',
        read_only => '',
            },
    'mute' => {
        datatype => 'int',
        base_name => 'mute',
        description => 'Indicates when the chat is muted.',
        format => '',
        read_only => '',
            },
    'last_message' => {
        datatype => 'string',
        base_name => 'lastMessage',
        description => 'The last message content of a chat.',
        format => '',
        read_only => '',
            },
    'direction' => {
        datatype => 'string',
        base_name => 'direction',
        description => 'Last message type: * **ci** - incoming call; * **co** - outgoing call; * **i** - incoming message; * **o** - outgoing message. ',
        format => '',
        read_only => '',
            },
    'reply_options_type' => {
        datatype => 'string',
        base_name => 'replyOptionsType',
        description => 'Used for chats prices.',
        format => '',
        read_only => '',
            },
    'from' => {
        datatype => 'string',
        base_name => 'from',
        description => 'If filled, the value will be used as a sender number for all outgoing messages of a chat.',
        format => '',
        read_only => '',
            },
    'muted_until' => {
        datatype => 'DATE_TIME',
        base_name => 'mutedUntil',
        description => 'Date and time until the chat will be muted.',
        format => '',
        read_only => '',
            },
    'time_left_mute' => {
        datatype => 'int',
        base_name => 'timeLeftMute',
        description => 'Time left untill the chat will be unmuted (seconds).',
        format => '',
        read_only => '',
            },
    'country' => {
        datatype => 'Country',
        base_name => 'country',
        description => '',
        format => '',
        read_only => '',
            },
    'pinned' => {
        datatype => 'boolean',
        base_name => 'pinned',
        description => 'Indicates when the chat is pinned.',
        format => '',
        read_only => '',
            },
    'type' => {
        datatype => 'string',
        base_name => 'type',
        description => 'Chat type.',
        format => '',
        read_only => '',
            },
    'sms_price' => {
        datatype => 'double',
        base_name => 'smsPrice',
        description => '',
        format => '',
        read_only => '',
            },
    'mms_price' => {
        datatype => 'double',
        base_name => 'mmsPrice',
        description => '',
        format => '',
        read_only => '',
            },
    'tags' => {
        datatype => 'ARRAY[Tag]',
        base_name => 'tags',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'id' => 'int',
    'original_id' => 'int',
    'phone' => 'string',
    'contact' => 'Contact',
    'unsubscribed_contact_id' => 'int',
    'unread' => 'int',
    'updated_at' => 'DATE_TIME',
    'status' => 'string',
    'mute' => 'int',
    'last_message' => 'string',
    'direction' => 'string',
    'reply_options_type' => 'string',
    'from' => 'string',
    'muted_until' => 'DATE_TIME',
    'time_left_mute' => 'int',
    'country' => 'Country',
    'pinned' => 'boolean',
    'type' => 'string',
    'sms_price' => 'double',
    'mms_price' => 'double',
    'tags' => 'ARRAY[Tag]'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'original_id' => 'originalId',
    'phone' => 'phone',
    'contact' => 'contact',
    'unsubscribed_contact_id' => 'unsubscribedContactId',
    'unread' => 'unread',
    'updated_at' => 'updatedAt',
    'status' => 'status',
    'mute' => 'mute',
    'last_message' => 'lastMessage',
    'direction' => 'direction',
    'reply_options_type' => 'replyOptionsType',
    'from' => 'from',
    'muted_until' => 'mutedUntil',
    'time_left_mute' => 'timeLeftMute',
    'country' => 'country',
    'pinned' => 'pinned',
    'type' => 'type',
    'sms_price' => 'smsPrice',
    'mms_price' => 'mmsPrice',
    'tags' => 'tags'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
