=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Net::Sms::TextMagicClient::Object::Contact;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Net::Sms::TextMagicClient::Object::ContactImage;
use Net::Sms::TextMagicClient::Object::ContactNote;
use Net::Sms::TextMagicClient::Object::Country;
use Net::Sms::TextMagicClient::Object::CustomFieldListItem;
use Net::Sms::TextMagicClient::Object::CustomFieldValues;
use Net::Sms::TextMagicClient::Object::List;
use Net::Sms::TextMagicClient::Object::Tag;
use Net::Sms::TextMagicClient::Object::User;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'Contact',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
        datatype => 'int',
        base_name => 'id',
        description => 'Contact ID.',
        format => '',
        read_only => '',
            },
    'favorited' => {
        datatype => 'boolean',
        base_name => 'favorited',
        description => 'Is the Contact favorite? [Favorite list](https://docs.textmagic.com/#operation/getFavorites).',
        format => '',
        read_only => '',
            },
    'blocked' => {
        datatype => 'boolean',
        base_name => 'blocked',
        description => 'Is the Contact blocked? [Blocked contacts](https://docs.textmagic.com/#operation/getBlockedContacts).',
        format => '',
        read_only => '',
            },
    'first_name' => {
        datatype => 'string',
        base_name => 'firstName',
        description => 'Contact first name.',
        format => '',
        read_only => '',
            },
    'last_name' => {
        datatype => 'string',
        base_name => 'lastName',
        description => 'Contact last name.',
        format => '',
        read_only => '',
            },
    'company_name' => {
        datatype => 'string',
        base_name => 'companyName',
        description => 'Company name.',
        format => '',
        read_only => '',
            },
    'phone' => {
        datatype => 'string',
        base_name => 'phone',
        description => 'Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).',
        format => '',
        read_only => '',
            },
    'email' => {
        datatype => 'string',
        base_name => 'email',
        description => 'Contact email address.',
        format => '',
        read_only => '',
            },
    'country' => {
        datatype => 'Country',
        base_name => 'country',
        description => '',
        format => '',
        read_only => '',
            },
    'custom_fields' => {
        datatype => 'ARRAY[CustomFieldListItem]',
        base_name => 'customFields',
        description => '',
        format => '',
        read_only => '',
            },
    'custom_field_values' => {
        datatype => 'ARRAY[CustomFieldValues]',
        base_name => 'customFieldValues',
        description => '',
        format => '',
        read_only => '',
            },
    'user' => {
        datatype => 'User',
        base_name => 'user',
        description => '',
        format => '',
        read_only => '',
            },
    'lists' => {
        datatype => 'ARRAY[List]',
        base_name => 'lists',
        description => '',
        format => '',
        read_only => '',
            },
    'owner' => {
        datatype => 'User',
        base_name => 'owner',
        description => '',
        format => '',
        read_only => '',
            },
    'tags' => {
        datatype => 'ARRAY[Tag]',
        base_name => 'tags',
        description => '',
        format => '',
        read_only => '',
            },
    'phone_type' => {
        datatype => 'string',
        base_name => 'phoneType',
        description => 'Phone number type: * **0** if it is fixed-line; * **1** if it is mobile; * **2** if it is mobile or fixed-line (in case we cannot distingush between fixed-line or mobile); * **3** if it is toll-free; * **4** if it is a premium rate phone; * **5** if it is a shared cost phone; * **6** if it is a VoIP; * **7** if it is a [Personal Number](); * **8** if it is a pager; * **9** if it is a Universal Access Number; * **10** if the phone type is unknown; * **-1** if the phone type is not yet processed or cannot be determined. ',
        format => '',
        read_only => '',
            },
    'avatar' => {
        datatype => 'ContactImage',
        base_name => 'avatar',
        description => '',
        format => '',
        read_only => '',
            },
    'notes' => {
        datatype => 'ARRAY[ContactNote]',
        base_name => 'notes',
        description => '',
        format => '',
        read_only => '',
            },
    'whatsapp_phone' => {
        datatype => 'string',
        base_name => 'whatsappPhone',
        description => 'Whatsapp phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'id' => 'int',
    'favorited' => 'boolean',
    'blocked' => 'boolean',
    'first_name' => 'string',
    'last_name' => 'string',
    'company_name' => 'string',
    'phone' => 'string',
    'email' => 'string',
    'country' => 'Country',
    'custom_fields' => 'ARRAY[CustomFieldListItem]',
    'custom_field_values' => 'ARRAY[CustomFieldValues]',
    'user' => 'User',
    'lists' => 'ARRAY[List]',
    'owner' => 'User',
    'tags' => 'ARRAY[Tag]',
    'phone_type' => 'string',
    'avatar' => 'ContactImage',
    'notes' => 'ARRAY[ContactNote]',
    'whatsapp_phone' => 'string'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'favorited' => 'favorited',
    'blocked' => 'blocked',
    'first_name' => 'firstName',
    'last_name' => 'lastName',
    'company_name' => 'companyName',
    'phone' => 'phone',
    'email' => 'email',
    'country' => 'country',
    'custom_fields' => 'customFields',
    'custom_field_values' => 'customFieldValues',
    'user' => 'user',
    'lists' => 'lists',
    'owner' => 'owner',
    'tags' => 'tags',
    'phone_type' => 'phoneType',
    'avatar' => 'avatar',
    'notes' => 'notes',
    'whatsapp_phone' => 'whatsappPhone'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
