=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Net::Sms::TextMagicClient::Object::Conversation;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Net::Sms::TextMagicClient::Object::File;
use Net::Sms::TextMagicClient::Object::MessagePayload;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'Conversation',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
        datatype => 'int',
        base_name => 'id',
        description => '',
        format => '',
        read_only => '',
            },
    'direction' => {
        datatype => 'string',
        base_name => 'direction',
        description => 'Message type: inbound or outbound. ',
        format => '',
        read_only => '',
            },
    'sender' => {
        datatype => 'string',
        base_name => 'sender',
        description => 'Sender phone number.',
        format => '',
        read_only => '',
            },
    'message_time' => {
        datatype => 'DATE_TIME',
        base_name => 'messageTime',
        description => 'Time when  the message arrived at Textmagic.',
        format => '',
        read_only => '',
            },
    'text' => {
        datatype => 'string',
        base_name => 'text',
        description => 'Message text.',
        format => '',
        read_only => '',
            },
    'receiver' => {
        datatype => 'string',
        base_name => 'receiver',
        description => 'Receiver&#39;s phone number.',
        format => '',
        read_only => '',
            },
    'status' => {
        datatype => 'string',
        base_name => 'status',
        description => 'Message status (for chats outbound only). See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.',
        format => '',
        read_only => '',
            },
    'first_name' => {
        datatype => 'string',
        base_name => 'firstName',
        description => 'Contact first name.',
        format => '',
        read_only => '',
            },
    'last_name' => {
        datatype => 'string',
        base_name => 'lastName',
        description => 'Contact last name.',
        format => '',
        read_only => '',
            },
    'session_id' => {
        datatype => 'int',
        base_name => 'sessionId',
        description => 'Session ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.',
        format => '',
        read_only => '',
            },
    'initiator_id' => {
        datatype => 'int',
        base_name => 'initiatorId',
        description => 'Initiator ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.',
        format => '',
        read_only => '',
            },
    'message_file_id' => {
        datatype => 'int',
        base_name => 'messageFileId',
        description => 'Message file id.',
        format => '',
        read_only => '',
            },
    'type' => {
        datatype => 'string',
        base_name => 'type',
        description => 'Message type.',
        format => '',
        read_only => '',
            },
    'chat_type' => {
        datatype => 'string',
        base_name => 'chatType',
        description => 'Chat type.',
        format => '',
        read_only => '',
            },
    'chat_id' => {
        datatype => 'int',
        base_name => 'chatId',
        description => 'Chat id.',
        format => '',
        read_only => '',
            },
    'is_edited' => {
        datatype => 'boolean',
        base_name => 'isEdited',
        description => '',
        format => '',
        read_only => '',
            },
    'error_code' => {
        datatype => 'string',
        base_name => 'errorCode',
        description => 'Error code.',
        format => '',
        read_only => '',
            },
    'files' => {
        datatype => 'ARRAY[File]',
        base_name => 'files',
        description => '',
        format => '',
        read_only => '',
            },
    'payload' => {
        datatype => 'MessagePayload',
        base_name => 'payload',
        description => '',
        format => '',
        read_only => '',
            },
    'avatar' => {
        datatype => 'string',
        base_name => 'avatar',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'id' => 'int',
    'direction' => 'string',
    'sender' => 'string',
    'message_time' => 'DATE_TIME',
    'text' => 'string',
    'receiver' => 'string',
    'status' => 'string',
    'first_name' => 'string',
    'last_name' => 'string',
    'session_id' => 'int',
    'initiator_id' => 'int',
    'message_file_id' => 'int',
    'type' => 'string',
    'chat_type' => 'string',
    'chat_id' => 'int',
    'is_edited' => 'boolean',
    'error_code' => 'string',
    'files' => 'ARRAY[File]',
    'payload' => 'MessagePayload',
    'avatar' => 'string'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'direction' => 'direction',
    'sender' => 'sender',
    'message_time' => 'messageTime',
    'text' => 'text',
    'receiver' => 'receiver',
    'status' => 'status',
    'first_name' => 'firstName',
    'last_name' => 'lastName',
    'session_id' => 'sessionId',
    'initiator_id' => 'initiatorId',
    'message_file_id' => 'messageFileId',
    'type' => 'type',
    'chat_type' => 'chatType',
    'chat_id' => 'chatId',
    'is_edited' => 'isEdited',
    'error_code' => 'errorCode',
    'files' => 'files',
    'payload' => 'payload',
    'avatar' => 'avatar'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
