=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Net::Sms::TextMagicClient::Object::DoEmailLookupResponse;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'DoEmailLookupResponse',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'address' => {
        datatype => 'string',
        base_name => 'address',
        description => 'The email address passed to the call.',
        format => '',
        read_only => '',
            },
    'status' => {
        datatype => 'string',
        base_name => 'status',
        description => 'The email is &#x60;valid&#x60; or &#x60;invalid&#x60;.',
        format => '',
        read_only => '',
            },
    'deliverability' => {
        datatype => 'string',
        base_name => 'deliverability',
        description => 'The delivery status of the email address is&#x60;deliverable&#x60;, &#x60;undeliverable&#x60;. or &#x60;unknown&#x60;.',
        format => '',
        read_only => '',
            },
    'reason' => {
        datatype => 'string',
        base_name => 'reason',
        description => 'The reason why the checked email is invalid/undeliverable.',
        format => '',
        read_only => '',
            },
    'risk' => {
        datatype => 'string',
        base_name => 'risk',
        description => 'The risk score of the email is&#x60;high&#x60;, &#x60;medium&#x60;, &#x60;low&#x60; or &#x60;null&#x60;.',
        format => '',
        read_only => '',
            },
    'address_type' => {
        datatype => 'string',
        base_name => 'addressType',
        description => 'The email address type (domain) is &#x60;free&#x60; or &#x60;corporate&#x60;.',
        format => '',
        read_only => '',
            },
    'is_disposable_address' => {
        datatype => 'boolean',
        base_name => 'isDisposableAddress',
        description => 'This is &#x60;true&#x60; if the domain is in the list of disposable email addresses; otherwise, it returns as &#x60;false&#x60;.',
        format => '',
        read_only => '',
            },
    'suggestion' => {
        datatype => 'string',
        base_name => 'suggestion',
        description => 'Null if nothing is suggested; however, if there is a potential typo in the email address, the closest suggestion is provided.',
        format => '',
        read_only => '',
            },
    'email_role' => {
        datatype => 'string',
        base_name => 'emailRole',
        description => 'Checks the mailbox part of the email to see whether it matches a specific role type (‘admin’, ‘sales’, ‘webmaster’).',
        format => '',
        read_only => '',
            },
    'local_part' => {
        datatype => 'string',
        base_name => 'localPart',
        description => 'The local part of the email address.',
        format => '',
        read_only => '',
            },
    'domain_part' => {
        datatype => 'string',
        base_name => 'domainPart',
        description => 'The domain part of the email address.',
        format => '',
        read_only => '',
            },
    'exchange' => {
        datatype => 'string',
        base_name => 'exchange',
        description => 'Email exchange server domain name (MX record value).',
        format => '',
        read_only => '',
            },
    'preference' => {
        datatype => 'int',
        base_name => 'preference',
        description => 'MX record preference.',
        format => '',
        read_only => '',
            },
    'is_in_white_list' => {
        datatype => 'boolean',
        base_name => 'isInWhiteList',
        description => '&#x60;true&#x60; if the email address exists in the Textmagic whitelist. ',
        format => '',
        read_only => '',
            },
    'is_in_black_list' => {
        datatype => 'boolean',
        base_name => 'isInBlackList',
        description => '&#x60;true&#x60; if the email address exists in the Textmagic blacklist. ',
        format => '',
        read_only => '',
            },
    'has_mx' => {
        datatype => 'boolean',
        base_name => 'hasMx',
        description => '&#x60;true&#x60; if the email address domain has an MX record. ',
        format => '',
        read_only => '',
            },
    'has_aa' => {
        datatype => 'boolean',
        base_name => 'hasAa',
        description => '&#x60;true&#x60; if the email address domain has an A record (IPv4). ',
        format => '',
        read_only => '',
            },
    'has_aaaa' => {
        datatype => 'boolean',
        base_name => 'hasAaaa',
        description => '&#x60;true&#x60; if the email address domain has an AAAA record (IPv6). ',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'address' => 'string',
    'status' => 'string',
    'deliverability' => 'string',
    'reason' => 'string',
    'risk' => 'string',
    'address_type' => 'string',
    'is_disposable_address' => 'boolean',
    'suggestion' => 'string',
    'email_role' => 'string',
    'local_part' => 'string',
    'domain_part' => 'string',
    'exchange' => 'string',
    'preference' => 'int',
    'is_in_white_list' => 'boolean',
    'is_in_black_list' => 'boolean',
    'has_mx' => 'boolean',
    'has_aa' => 'boolean',
    'has_aaaa' => 'boolean'
} );

__PACKAGE__->attribute_map( {
    'address' => 'address',
    'status' => 'status',
    'deliverability' => 'deliverability',
    'reason' => 'reason',
    'risk' => 'risk',
    'address_type' => 'addressType',
    'is_disposable_address' => 'isDisposableAddress',
    'suggestion' => 'suggestion',
    'email_role' => 'emailRole',
    'local_part' => 'localPart',
    'domain_part' => 'domainPart',
    'exchange' => 'exchange',
    'preference' => 'preference',
    'is_in_white_list' => 'isInWhiteList',
    'is_in_black_list' => 'isInBlackList',
    'has_mx' => 'hasMx',
    'has_aa' => 'hasAa',
    'has_aaaa' => 'hasAaaa'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
