=begin comment

Textmagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package Net::Sms::TextMagicClient::Object::GetStateResponse;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Textmagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'GetStateResponse',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'system_cache_clear' => {
    	datatype => 'int',
    	base_name => 'systemCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'system_exit' => {
    	datatype => 'int',
    	base_name => 'systemExit',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'system_alert' => {
    	datatype => 'int',
    	base_name => 'systemAlert',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'system_account_state_changed' => {
    	datatype => 'int',
    	base_name => 'systemAccountStateChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'system_account_closed' => {
    	datatype => 'int',
    	base_name => 'systemAccountClosed',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'system_account_additional_fields' => {
    	datatype => 'int',
    	base_name => 'systemAccountAdditionalFields',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'system_account_permissions_changed' => {
    	datatype => 'int',
    	base_name => 'systemAccountPermissionsChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'user_profile_changed' => {
    	datatype => 'int',
    	base_name => 'userProfileChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'user_balance_changed' => {
    	datatype => 'int',
    	base_name => 'userBalanceChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'user_impersonation_end' => {
    	datatype => 'int',
    	base_name => 'userImpersonationEnd',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_deleted' => {
    	datatype => 'int',
    	base_name => 'messageDeleted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_incoming' => {
    	datatype => 'int',
    	base_name => 'messageIncoming',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_incoming_deleted' => {
    	datatype => 'int',
    	base_name => 'messageIncomingDeleted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_state_changed' => {
    	datatype => 'int',
    	base_name => 'messageStateChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_bulk_end' => {
    	datatype => 'int',
    	base_name => 'messageBulkEnd',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_wipe_end' => {
    	datatype => 'int',
    	base_name => 'messageWipeEnd',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_sent' => {
    	datatype => 'int',
    	base_name => 'messageSent',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_session_deleted' => {
    	datatype => 'int',
    	base_name => 'messageSessionDeleted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_cache_clear' => {
    	datatype => 'int',
    	base_name => 'messageCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_incoming_cache_clear' => {
    	datatype => 'int',
    	base_name => 'messageIncomingCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_schedule_added' => {
    	datatype => 'int',
    	base_name => 'messageScheduleAdded',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_schedule_state_changed' => {
    	datatype => 'int',
    	base_name => 'messageScheduleStateChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_schedule_deleted' => {
    	datatype => 'int',
    	base_name => 'messageScheduleDeleted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_schedule_not_sent_state_changed' => {
    	datatype => 'int',
    	base_name => 'messageScheduleNotSentStateChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_schedule_cache_clear' => {
    	datatype => 'int',
    	base_name => 'messageScheduleCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'message_template_cache_clear' => {
    	datatype => 'int',
    	base_name => 'messageTemplateCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'call_finished' => {
    	datatype => 'int',
    	base_name => 'callFinished',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_created' => {
    	datatype => 'int',
    	base_name => 'chatCreated',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_marked_as_read' => {
    	datatype => 'int',
    	base_name => 'chatMarkedAsRead',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_muted' => {
    	datatype => 'int',
    	base_name => 'chatMuted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_unmuted' => {
    	datatype => 'int',
    	base_name => 'chatUnmuted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_pinned' => {
    	datatype => 'int',
    	base_name => 'chatPinned',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_unpinned' => {
    	datatype => 'int',
    	base_name => 'chatUnpinned',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_deleted' => {
    	datatype => 'int',
    	base_name => 'chatDeleted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_closed' => {
    	datatype => 'int',
    	base_name => 'chatClosed',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_reopened' => {
    	datatype => 'int',
    	base_name => 'chatReopened',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_cache_clear' => {
    	datatype => 'int',
    	base_name => 'chatCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_read' => {
    	datatype => 'int',
    	base_name => 'chatRead',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_unread' => {
    	datatype => 'int',
    	base_name => 'chatUnread',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'contact_added' => {
    	datatype => 'int',
    	base_name => 'contactAdded',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'contact_deleted' => {
    	datatype => 'int',
    	base_name => 'contactDeleted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'contact_state_changed' => {
    	datatype => 'int',
    	base_name => 'contactStateChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'list_added' => {
    	datatype => 'int',
    	base_name => 'listAdded',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'list_deleted' => {
    	datatype => 'int',
    	base_name => 'listDeleted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'list_state_changed' => {
    	datatype => 'int',
    	base_name => 'listStateChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'contact_wipe_end' => {
    	datatype => 'int',
    	base_name => 'contactWipeEnd',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'contact_import_end' => {
    	datatype => 'int',
    	base_name => 'contactImportEnd',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'contact_cache_clear' => {
    	datatype => 'int',
    	base_name => 'contactCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'list_cache_clear' => {
    	datatype => 'int',
    	base_name => 'listCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'custom_fields_cache_clear' => {
    	datatype => 'int',
    	base_name => 'customFieldsCacheClear',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'progress_carrier_bulk_lookup' => {
    	datatype => 'int',
    	base_name => 'progressCarrierBulkLookup',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'progress_email_bulk_lookup' => {
    	datatype => 'int',
    	base_name => 'progressEmailBulkLookup',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'progress_sub_account_bulk_import' => {
    	datatype => 'int',
    	base_name => 'progressSubAccountBulkImport',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'progress_contact_bulk_import' => {
    	datatype => 'int',
    	base_name => 'progressContactBulkImport',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'force_refresh_web_app' => {
    	datatype => 'int',
    	base_name => 'forceRefreshWebApp',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_sender_settings_changed' => {
    	datatype => 'int',
    	base_name => 'chatSenderSettingsChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'country_sender_settings_changed' => {
    	datatype => 'int',
    	base_name => 'countrySenderSettingsChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_summary_chunk' => {
    	datatype => 'int',
    	base_name => 'chatSummaryChunk',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_ways_to_reply_chunk' => {
    	datatype => 'int',
    	base_name => 'chatWaysToReplyChunk',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'chat_suggested_reply_chunk' => {
    	datatype => 'int',
    	base_name => 'chatSuggestedReplyChunk',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'user_subscription_changed' => {
    	datatype => 'int',
    	base_name => 'userSubscriptionChanged',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'user_subscription_deleted' => {
    	datatype => 'int',
    	base_name => 'userSubscriptionDeleted',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'system_cache_clear' => 'int',
    'system_exit' => 'int',
    'system_alert' => 'int',
    'system_account_state_changed' => 'int',
    'system_account_closed' => 'int',
    'system_account_additional_fields' => 'int',
    'system_account_permissions_changed' => 'int',
    'user_profile_changed' => 'int',
    'user_balance_changed' => 'int',
    'user_impersonation_end' => 'int',
    'message_deleted' => 'int',
    'message_incoming' => 'int',
    'message_incoming_deleted' => 'int',
    'message_state_changed' => 'int',
    'message_bulk_end' => 'int',
    'message_wipe_end' => 'int',
    'message_sent' => 'int',
    'message_session_deleted' => 'int',
    'message_cache_clear' => 'int',
    'message_incoming_cache_clear' => 'int',
    'message_schedule_added' => 'int',
    'message_schedule_state_changed' => 'int',
    'message_schedule_deleted' => 'int',
    'message_schedule_not_sent_state_changed' => 'int',
    'message_schedule_cache_clear' => 'int',
    'message_template_cache_clear' => 'int',
    'call_finished' => 'int',
    'chat_created' => 'int',
    'chat_marked_as_read' => 'int',
    'chat_muted' => 'int',
    'chat_unmuted' => 'int',
    'chat_pinned' => 'int',
    'chat_unpinned' => 'int',
    'chat_deleted' => 'int',
    'chat_closed' => 'int',
    'chat_reopened' => 'int',
    'chat_cache_clear' => 'int',
    'chat_read' => 'int',
    'chat_unread' => 'int',
    'contact_added' => 'int',
    'contact_deleted' => 'int',
    'contact_state_changed' => 'int',
    'list_added' => 'int',
    'list_deleted' => 'int',
    'list_state_changed' => 'int',
    'contact_wipe_end' => 'int',
    'contact_import_end' => 'int',
    'contact_cache_clear' => 'int',
    'list_cache_clear' => 'int',
    'custom_fields_cache_clear' => 'int',
    'progress_carrier_bulk_lookup' => 'int',
    'progress_email_bulk_lookup' => 'int',
    'progress_sub_account_bulk_import' => 'int',
    'progress_contact_bulk_import' => 'int',
    'force_refresh_web_app' => 'int',
    'chat_sender_settings_changed' => 'int',
    'country_sender_settings_changed' => 'int',
    'chat_summary_chunk' => 'int',
    'chat_ways_to_reply_chunk' => 'int',
    'chat_suggested_reply_chunk' => 'int',
    'user_subscription_changed' => 'int',
    'user_subscription_deleted' => 'int'
} );

__PACKAGE__->attribute_map( {
    'system_cache_clear' => 'systemCacheClear',
    'system_exit' => 'systemExit',
    'system_alert' => 'systemAlert',
    'system_account_state_changed' => 'systemAccountStateChanged',
    'system_account_closed' => 'systemAccountClosed',
    'system_account_additional_fields' => 'systemAccountAdditionalFields',
    'system_account_permissions_changed' => 'systemAccountPermissionsChanged',
    'user_profile_changed' => 'userProfileChanged',
    'user_balance_changed' => 'userBalanceChanged',
    'user_impersonation_end' => 'userImpersonationEnd',
    'message_deleted' => 'messageDeleted',
    'message_incoming' => 'messageIncoming',
    'message_incoming_deleted' => 'messageIncomingDeleted',
    'message_state_changed' => 'messageStateChanged',
    'message_bulk_end' => 'messageBulkEnd',
    'message_wipe_end' => 'messageWipeEnd',
    'message_sent' => 'messageSent',
    'message_session_deleted' => 'messageSessionDeleted',
    'message_cache_clear' => 'messageCacheClear',
    'message_incoming_cache_clear' => 'messageIncomingCacheClear',
    'message_schedule_added' => 'messageScheduleAdded',
    'message_schedule_state_changed' => 'messageScheduleStateChanged',
    'message_schedule_deleted' => 'messageScheduleDeleted',
    'message_schedule_not_sent_state_changed' => 'messageScheduleNotSentStateChanged',
    'message_schedule_cache_clear' => 'messageScheduleCacheClear',
    'message_template_cache_clear' => 'messageTemplateCacheClear',
    'call_finished' => 'callFinished',
    'chat_created' => 'chatCreated',
    'chat_marked_as_read' => 'chatMarkedAsRead',
    'chat_muted' => 'chatMuted',
    'chat_unmuted' => 'chatUnmuted',
    'chat_pinned' => 'chatPinned',
    'chat_unpinned' => 'chatUnpinned',
    'chat_deleted' => 'chatDeleted',
    'chat_closed' => 'chatClosed',
    'chat_reopened' => 'chatReopened',
    'chat_cache_clear' => 'chatCacheClear',
    'chat_read' => 'chatRead',
    'chat_unread' => 'chatUnread',
    'contact_added' => 'contactAdded',
    'contact_deleted' => 'contactDeleted',
    'contact_state_changed' => 'contactStateChanged',
    'list_added' => 'listAdded',
    'list_deleted' => 'listDeleted',
    'list_state_changed' => 'listStateChanged',
    'contact_wipe_end' => 'contactWipeEnd',
    'contact_import_end' => 'contactImportEnd',
    'contact_cache_clear' => 'contactCacheClear',
    'list_cache_clear' => 'listCacheClear',
    'custom_fields_cache_clear' => 'customFieldsCacheClear',
    'progress_carrier_bulk_lookup' => 'progressCarrierBulkLookup',
    'progress_email_bulk_lookup' => 'progressEmailBulkLookup',
    'progress_sub_account_bulk_import' => 'progressSubAccountBulkImport',
    'progress_contact_bulk_import' => 'progressContactBulkImport',
    'force_refresh_web_app' => 'forceRefreshWebApp',
    'chat_sender_settings_changed' => 'chatSenderSettingsChanged',
    'country_sender_settings_changed' => 'countrySenderSettingsChanged',
    'chat_summary_chunk' => 'chatSummaryChunk',
    'chat_ways_to_reply_chunk' => 'chatWaysToReplyChunk',
    'chat_suggested_reply_chunk' => 'chatSuggestedReplyChunk',
    'user_subscription_changed' => 'userSubscriptionChanged',
    'user_subscription_deleted' => 'userSubscriptionDeleted'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
