=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Net::Sms::TextMagicClient::Object::MessagesIcs;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Net::Sms::TextMagicClient::Object::MessageSession;
use Net::Sms::TextMagicClient::Object::MessagesIcsParameters;
use Net::Sms::TextMagicClient::Object::MessagesIcsTextParameters;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'MessagesIcs',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
        datatype => 'int',
        base_name => 'id',
        description => 'Schedule ID.',
        format => '',
        read_only => '',
            },
    'next_send' => {
        datatype => 'DATE_TIME',
        base_name => 'nextSend',
        description => 'The next send date in [ISO 8601](https://en.wikipedia.org/?title&#x3D;ISO_8601) format. ',
        format => '',
        read_only => '',
            },
    'rrule' => {
        datatype => 'string',
        base_name => 'rrule',
        description => '[iCal RRULE](http://www.kanzaki.com/docs/ical/rrule.html) string. ',
        format => '',
        read_only => '',
            },
    'session' => {
        datatype => 'MessageSession',
        base_name => 'session',
        description => '',
        format => '',
        read_only => '',
            },
    'last_sent' => {
        datatype => 'DATE_TIME',
        base_name => 'lastSent',
        description => 'The date and time when the last message was sent.',
        format => '',
        read_only => '',
            },
    'contact_name' => {
        datatype => 'string',
        base_name => 'contactName',
        description => 'Aggregated contact information. If the message was scheduled to be sent to a single contact, a full name will be returned here. Otherwise, a total amount of contacts will be returned.',
        format => '',
        read_only => '',
            },
    'parameters' => {
        datatype => 'MessagesIcsParameters',
        base_name => 'parameters',
        description => '',
        format => '',
        read_only => '',
            },
    'type' => {
        datatype => 'string',
        base_name => 'type',
        description => '',
        format => '',
        read_only => '',
            },
    'summary' => {
        datatype => 'string',
        base_name => 'summary',
        description => 'A human-readable summary of the sending schedule.',
        format => '',
        read_only => '',
            },
    'text_parameters' => {
        datatype => 'MessagesIcsTextParameters',
        base_name => 'textParameters',
        description => '',
        format => '',
        read_only => '',
            },
    'first_occurrence' => {
        datatype => 'DATE_TIME',
        base_name => 'firstOccurrence',
        description => 'First occurence date.',
        format => '',
        read_only => '',
            },
    'last_occurrence' => {
        datatype => 'DATE_TIME',
        base_name => 'lastOccurrence',
        description => 'Last occurence date (could be &#x60;null&#x60; if the schedule is endless).',
        format => '',
        read_only => '',
            },
    'recipients_count' => {
        datatype => 'int',
        base_name => 'recipientsCount',
        description => 'Amount of actual recipients.',
        format => '',
        read_only => '',
            },
    'timezone' => {
        datatype => 'string',
        base_name => 'timezone',
        description => 'User-friendly timezone name (with spaces replaced by underscores).',
        format => '',
        read_only => '',
            },
    'completed' => {
        datatype => 'boolean',
        base_name => 'completed',
        description => 'Indicates that scheduling has been completed.',
        format => '',
        read_only => '',
            },
    'avatar' => {
        datatype => 'string',
        base_name => 'avatar',
        description => 'A relative link to the contact avatar.',
        format => '',
        read_only => '',
            },
    'created_at' => {
        datatype => 'DATE_TIME',
        base_name => 'createdAt',
        description => 'Scheduling creation time.',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'id' => 'int',
    'next_send' => 'DATE_TIME',
    'rrule' => 'string',
    'session' => 'MessageSession',
    'last_sent' => 'DATE_TIME',
    'contact_name' => 'string',
    'parameters' => 'MessagesIcsParameters',
    'type' => 'string',
    'summary' => 'string',
    'text_parameters' => 'MessagesIcsTextParameters',
    'first_occurrence' => 'DATE_TIME',
    'last_occurrence' => 'DATE_TIME',
    'recipients_count' => 'int',
    'timezone' => 'string',
    'completed' => 'boolean',
    'avatar' => 'string',
    'created_at' => 'DATE_TIME'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'next_send' => 'nextSend',
    'rrule' => 'rrule',
    'session' => 'session',
    'last_sent' => 'lastSent',
    'contact_name' => 'contactName',
    'parameters' => 'parameters',
    'type' => 'type',
    'summary' => 'summary',
    'text_parameters' => 'textParameters',
    'first_occurrence' => 'firstOccurrence',
    'last_occurrence' => 'lastOccurrence',
    'recipients_count' => 'recipientsCount',
    'timezone' => 'timezone',
    'completed' => 'completed',
    'avatar' => 'avatar',
    'created_at' => 'createdAt'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
