=begin comment

Textmagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package Net::Sms::TextMagicClient::Object::OutboundEmailResponse;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Textmagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'OutboundEmailResponse',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => 'Outbound email ID.',
    	format => '',
    	read_only => '',
    		},
    'send_time' => {
    	datatype => 'DateTime',
    	base_name => 'sendTime',
    	description => 'Email send timestamp.',
    	format => '',
    	read_only => '',
    		},
    'from_name' => {
    	datatype => 'string',
    	base_name => 'fromName',
    	description => 'Sender name.',
    	format => '',
    	read_only => '',
    		},
    'from_email' => {
    	datatype => 'string',
    	base_name => 'fromEmail',
    	description => 'Sender email address.',
    	format => '',
    	read_only => '',
    		},
    'reply_to_email' => {
    	datatype => 'string',
    	base_name => 'replyToEmail',
    	description => 'Reply-to email address.',
    	format => '',
    	read_only => '',
    		},
    'recipient_full_name' => {
    	datatype => 'string',
    	base_name => 'recipientFullName',
    	description => 'Recipient&#39;s full name.',
    	format => '',
    	read_only => '',
    		},
    'recipient_email' => {
    	datatype => 'string',
    	base_name => 'recipientEmail',
    	description => 'Recipient&#39;s email address.',
    	format => '',
    	read_only => '',
    		},
    'email_subject' => {
    	datatype => 'string',
    	base_name => 'emailSubject',
    	description => 'Email subject line.',
    	format => '',
    	read_only => '',
    		},
    'email_content' => {
    	datatype => 'string',
    	base_name => 'emailContent',
    	description => 'HTML email content.',
    	format => '',
    	read_only => '',
    		},
    'source' => {
    	datatype => 'string',
    	base_name => 'source',
    	description => 'Source of the outbound email.',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'string',
    	base_name => 'status',
    	description => 'Current email status.',
    	format => '',
    	read_only => '',
    		},
    'cost' => {
    	datatype => 'double',
    	base_name => 'cost',
    	description => 'Cost of sending this email.',
    	format => '',
    	read_only => '',
    		},
    'status_reason' => {
    	datatype => 'string',
    	base_name => 'statusReason',
    	description => 'Detailed status reason.',
    	format => '',
    	read_only => '',
    		},
    'contact_id' => {
    	datatype => 'int',
    	base_name => 'contactId',
    	description => 'Associated contact ID.',
    	format => '',
    	read_only => '',
    		},
    'initiator_id' => {
    	datatype => 'int',
    	base_name => 'initiatorId',
    	description => 'ID of user who initiated the email.',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'id' => 'int',
    'send_time' => 'DateTime',
    'from_name' => 'string',
    'from_email' => 'string',
    'reply_to_email' => 'string',
    'recipient_full_name' => 'string',
    'recipient_email' => 'string',
    'email_subject' => 'string',
    'email_content' => 'string',
    'source' => 'string',
    'status' => 'string',
    'cost' => 'double',
    'status_reason' => 'string',
    'contact_id' => 'int',
    'initiator_id' => 'int'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'send_time' => 'sendTime',
    'from_name' => 'fromName',
    'from_email' => 'fromEmail',
    'reply_to_email' => 'replyToEmail',
    'recipient_full_name' => 'recipientFullName',
    'recipient_email' => 'recipientEmail',
    'email_subject' => 'emailSubject',
    'email_content' => 'emailContent',
    'source' => 'source',
    'status' => 'status',
    'cost' => 'cost',
    'status_reason' => 'statusReason',
    'contact_id' => 'contactId',
    'initiator_id' => 'initiatorId'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
