=begin comment

Textmagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package Net::Sms::TextMagicClient::Object::ScheduledEmailCampaignDetails;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Net::Sms::TextMagicClient::Object::UserPersonalInfo;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Textmagic API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'ScheduledEmailCampaignDetails',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => 'Unique scheduled campaign ID.',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'string',
    	base_name => 'status',
    	description => 'Current scheduled campaign status.',
    	format => '',
    	read_only => '',
    		},
    'email_sender_id' => {
    	datatype => 'int',
    	base_name => 'emailSenderId',
    	description => 'Email sender ID used for this campaign.',
    	format => '',
    	read_only => '',
    		},
    'start_at' => {
    	datatype => 'DateTime',
    	base_name => 'startAt',
    	description => 'Scheduled start timestamp (UTC).',
    	format => '',
    	read_only => '',
    		},
    'end_at' => {
    	datatype => 'DateTime',
    	base_name => 'endAt',
    	description => 'End timestamp for recurring campaigns (UTC).',
    	format => '',
    	read_only => '',
    		},
    'next_send_at' => {
    	datatype => 'DateTime',
    	base_name => 'nextSendAt',
    	description => 'Next scheduled send timestamp (UTC).',
    	format => '',
    	read_only => '',
    		},
    'created_by' => {
    	datatype => 'UserPersonalInfo',
    	base_name => 'createdBy',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'createdAt',
    	description => 'Campaign creation timestamp.',
    	format => '',
    	read_only => '',
    		},
    'updated_at' => {
    	datatype => 'DateTime',
    	base_name => 'updatedAt',
    	description => 'Last update timestamp.',
    	format => '',
    	read_only => '',
    		},
    'type' => {
    	datatype => 'string',
    	base_name => 'type',
    	description => 'Campaign recurrence type.',
    	format => '',
    	read_only => '',
    		},
    'from_name' => {
    	datatype => 'string',
    	base_name => 'fromName',
    	description => 'Sender name displayed in recipient&#39;s inbox.',
    	format => '',
    	read_only => '',
    		},
    'from_email' => {
    	datatype => 'string',
    	base_name => 'fromEmail',
    	description => 'Sender email address.',
    	format => '',
    	read_only => '',
    		},
    'reply_to_email' => {
    	datatype => 'string',
    	base_name => 'replyToEmail',
    	description => 'Reply-to email address.',
    	format => '',
    	read_only => '',
    		},
    'subject' => {
    	datatype => 'string',
    	base_name => 'subject',
    	description => 'Email subject line.',
    	format => '',
    	read_only => '',
    		},
    'html' => {
    	datatype => 'string',
    	base_name => 'html',
    	description => 'HTML email content.',
    	format => '',
    	read_only => '',
    		},
    'recipients_count' => {
    	datatype => 'int',
    	base_name => 'recipientsCount',
    	description => 'Number of recipients for this campaign.',
    	format => '',
    	read_only => '',
    		},
    'sending_timezone' => {
    	datatype => 'string',
    	base_name => 'sendingTimezone',
    	description => 'Timezone for sending the campaign.',
    	format => '',
    	read_only => '',
    		},
    'rrule' => {
    	datatype => 'string',
    	base_name => 'rrule',
    	description => 'RFC 5545 recurrence rule for recurring campaigns.',
    	format => '',
    	read_only => '',
    		},
    'occurrence_summary' => {
    	datatype => 'string',
    	base_name => 'occurrenceSummary',
    	description => 'Human-readable schedule description.',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'id' => 'int',
    'status' => 'string',
    'email_sender_id' => 'int',
    'start_at' => 'DateTime',
    'end_at' => 'DateTime',
    'next_send_at' => 'DateTime',
    'created_by' => 'UserPersonalInfo',
    'created_at' => 'DateTime',
    'updated_at' => 'DateTime',
    'type' => 'string',
    'from_name' => 'string',
    'from_email' => 'string',
    'reply_to_email' => 'string',
    'subject' => 'string',
    'html' => 'string',
    'recipients_count' => 'int',
    'sending_timezone' => 'string',
    'rrule' => 'string',
    'occurrence_summary' => 'string'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'status' => 'status',
    'email_sender_id' => 'emailSenderId',
    'start_at' => 'startAt',
    'end_at' => 'endAt',
    'next_send_at' => 'nextSendAt',
    'created_by' => 'createdBy',
    'created_at' => 'createdAt',
    'updated_at' => 'updatedAt',
    'type' => 'type',
    'from_name' => 'fromName',
    'from_email' => 'fromEmail',
    'reply_to_email' => 'replyToEmail',
    'subject' => 'subject',
    'html' => 'html',
    'recipients_count' => 'recipientsCount',
    'sending_timezone' => 'sendingTimezone',
    'rrule' => 'rrule',
    'occurrence_summary' => 'occurrenceSummary'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
