=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Net::Sms::TextMagicClient::Object::SendMessageRequest;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'SendMessageRequest',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'text' => {
        datatype => 'string',
        base_name => 'text',
        description => 'Message text. Required if the **template_id** is not set.',
        format => '',
        read_only => '',
            },
    'template_id' => {
        datatype => 'int',
        base_name => 'templateId',
        description => 'Template used instead of message text. Required if the **text** is not set.',
        format => '',
        read_only => '',
            },
    'sending_time' => {
        datatype => 'int',
        base_name => 'sendingTime',
        description => 'DEPRECATED, consider using sendingDateTime and sendingTimezone parameters instead: Optional (required with rrule set). Message sending time in unix timestamp format. Default is now.',
        format => '',
        read_only => '',
            },
    'sending_date_time' => {
        datatype => 'string',
        base_name => 'sendingDateTime',
        description => 'Sending time in Y-m-d H:i:s format (e.g. 2022-05-27 13:05:10). This time is relative to **sendingTimezone**. Note: for correct operation, the value of seconds must not be less than 10.',
        format => '',
        read_only => '',
            },
    'sending_timezone' => {
        datatype => 'string',
        base_name => 'sendingTimezone',
        description => 'ID or ISO-name of timezone used for sending when sendingDateTime parameter is set. E.g. if you specify sendingDateTime &#x3D; \\\&quot;2016-05-27 13:02:33\\\&quot; and sendingTimezone &#x3D; \\\&quot;America/Buenos_Aires\\\&quot;, your message will be sent at May 27, 2016 13:02:33 Buenos Aires time, or 16:02:33 UTC. Default is account timezone.',
        format => '',
        read_only => '',
            },
    'contacts' => {
        datatype => 'string',
        base_name => 'contacts',
        description => 'Comma separated array of contact resources id message will be sent to.',
        format => '',
        read_only => '',
            },
    'lists' => {
        datatype => 'string',
        base_name => 'lists',
        description => 'Comma separated array of list resources id message will be sent to.',
        format => '',
        read_only => '',
            },
    'phones' => {
        datatype => 'string',
        base_name => 'phones',
        description => 'Comma separated array of E.164 phone numbers message will be sent to.',
        format => '',
        read_only => '',
            },
    'cut_extra' => {
        datatype => 'boolean',
        base_name => 'cutExtra',
        description => 'Should sending method cut extra characters which not fit supplied partsCount or return 400 Bad request response instead.',
        format => '',
        read_only => '',
            },
    'parts_count' => {
        datatype => 'int',
        base_name => 'partsCount',
        description => 'Maximum message parts count (Textmagic allows sending 1 to 6 message parts).',
        format => '',
        read_only => '',
            },
    'reference_id' => {
        datatype => 'int',
        base_name => 'referenceId',
        description => 'Custom message reference id which can be used in your application infrastructure.',
        format => '',
        read_only => '',
            },
    'from' => {
        datatype => 'string',
        base_name => 'from',
        description => 'One of allowed Sender ID (phone number or alphanumeric sender ID). If specified Sender ID is not allowed for some destinations, a fallback default Sender ID will be used to ensure delivery. See [Get timezones](https://docs.textmagic.com/#tag/Sender-IDs).',
        format => '',
        read_only => '',
            },
    'rrule' => {
        datatype => 'string',
        base_name => 'rrule',
        description => 'iCal RRULE parameter to create recurrent scheduled messages. When used, sendingTime is mandatory as start point of sending. See https://www.textmagic.com/free-tools/rrule-generator for format details.',
        format => '',
        read_only => '',
            },
    'create_chat' => {
        datatype => 'boolean',
        base_name => 'createChat',
        description => 'Should sending method try to create new Chat (if not exist) with specified recipients?',
        format => '',
        read_only => '',
            },
    'tts' => {
        datatype => 'boolean',
        base_name => 'tts',
        description => 'Send a Text-to-Speech message.',
        format => '',
        read_only => '',
            },
    'local' => {
        datatype => 'boolean',
        base_name => 'local',
        description => 'Treat phone numbers passed in the \\&#39;phones\\&#39; field as local.',
        format => '',
        read_only => '',
            },
    'local_country' => {
        datatype => 'string',
        base_name => 'localCountry',
        description => 'The 2-letter ISO country code for local phone numbers, used when \\&#39;local\\&#39; is set to true. Default is the account country.',
        format => '',
        read_only => '',
            },
    'destination' => {
        datatype => 'string',
        base_name => 'destination',
        description => 'Messsage destination type allowed [mms, tts].',
        format => '',
        read_only => '',
            },
    'resources' => {
        datatype => 'string',
        base_name => 'resources',
        description => 'File name from mms attachment response (named as resource)',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'text' => 'string',
    'template_id' => 'int',
    'sending_time' => 'int',
    'sending_date_time' => 'string',
    'sending_timezone' => 'string',
    'contacts' => 'string',
    'lists' => 'string',
    'phones' => 'string',
    'cut_extra' => 'boolean',
    'parts_count' => 'int',
    'reference_id' => 'int',
    'from' => 'string',
    'rrule' => 'string',
    'create_chat' => 'boolean',
    'tts' => 'boolean',
    'local' => 'boolean',
    'local_country' => 'string',
    'destination' => 'string',
    'resources' => 'string'
} );

__PACKAGE__->attribute_map( {
    'text' => 'text',
    'template_id' => 'templateId',
    'sending_time' => 'sendingTime',
    'sending_date_time' => 'sendingDateTime',
    'sending_timezone' => 'sendingTimezone',
    'contacts' => 'contacts',
    'lists' => 'lists',
    'phones' => 'phones',
    'cut_extra' => 'cutExtra',
    'parts_count' => 'partsCount',
    'reference_id' => 'referenceId',
    'from' => 'from',
    'rrule' => 'rrule',
    'create_chat' => 'createChat',
    'tts' => 'tts',
    'local' => 'local',
    'local_country' => 'localCountry',
    'destination' => 'destination',
    'resources' => 'resources'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
