=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Net::Sms::TextMagicClient::Object::User;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Net::Sms::TextMagicClient::Object::Country;
use Net::Sms::TextMagicClient::Object::Currency;
use Net::Sms::TextMagicClient::Object::Timezone;
use Net::Sms::TextMagicClient::Object::UserImage;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Textmagic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "Net::Sms::TextMagicClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'User',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
        datatype => 'int',
        base_name => 'id',
        description => 'User ID.',
        format => '',
        read_only => '',
            },
    'display_time_format' => {
        datatype => 'string',
        base_name => 'displayTimeFormat',
        description => 'User&#39;s preferred format of time display: * *12h* - AM/PM format; * *24h* - 24-hour clock format. ',
        format => '',
        read_only => '',
            },
    'username' => {
        datatype => 'string',
        base_name => 'username',
        description => 'Username.',
        format => '',
        read_only => '',
            },
    'first_name' => {
        datatype => 'string',
        base_name => 'firstName',
        description => 'Account first name.',
        format => '',
        read_only => '',
            },
    'last_name' => {
        datatype => 'string',
        base_name => 'lastName',
        description => 'Account last name.',
        format => '',
        read_only => '',
            },
    'email' => {
        datatype => 'string',
        base_name => 'email',
        description => 'User email address.',
        format => '',
        read_only => '',
            },
    'status' => {
        datatype => 'string',
        base_name => 'status',
        description => 'Current account status: * **A** for Active; * **T** for Trial. ',
        format => '',
        read_only => '',
            },
    'balance' => {
        datatype => 'double',
        base_name => 'balance',
        description => 'Account balance (in account currency).',
        format => '',
        read_only => '',
            },
    'phone' => {
        datatype => 'string',
        base_name => 'phone',
        description => 'User&#39;s phone number.',
        format => '',
        read_only => '',
            },
    'company' => {
        datatype => 'string',
        base_name => 'company',
        description => 'Account company name.',
        format => '',
        read_only => '',
            },
    'currency' => {
        datatype => 'Currency',
        base_name => 'currency',
        description => '',
        format => '',
        read_only => '',
            },
    'country' => {
        datatype => 'Country',
        base_name => 'country',
        description => '',
        format => '',
        read_only => '',
            },
    'timezone' => {
        datatype => 'Timezone',
        base_name => 'timezone',
        description => '',
        format => '',
        read_only => '',
            },
    'subaccount_type' => {
        datatype => 'string',
        base_name => 'subaccountType',
        description => 'Type of account: * **P** for Parent User; * **A** for Administrator Sub-Account; * **U** for Regular User. ',
        format => '',
        read_only => '',
            },
    'email_accepted' => {
        datatype => 'boolean',
        base_name => 'emailAccepted',
        description => 'Does the account have a confirmed email?',
        format => '',
        read_only => '',
            },
    'phone_accepted' => {
        datatype => 'boolean',
        base_name => 'phoneAccepted',
        description => 'Does the account have a confirmed phone number?',
        format => '',
        read_only => '',
            },
    'avatar' => {
        datatype => 'UserImage',
        base_name => 'avatar',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'id' => 'int',
    'display_time_format' => 'string',
    'username' => 'string',
    'first_name' => 'string',
    'last_name' => 'string',
    'email' => 'string',
    'status' => 'string',
    'balance' => 'double',
    'phone' => 'string',
    'company' => 'string',
    'currency' => 'Currency',
    'country' => 'Country',
    'timezone' => 'Timezone',
    'subaccount_type' => 'string',
    'email_accepted' => 'boolean',
    'phone_accepted' => 'boolean',
    'avatar' => 'UserImage'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'display_time_format' => 'displayTimeFormat',
    'username' => 'username',
    'first_name' => 'firstName',
    'last_name' => 'lastName',
    'email' => 'email',
    'status' => 'status',
    'balance' => 'balance',
    'phone' => 'phone',
    'company' => 'company',
    'currency' => 'currency',
    'country' => 'country',
    'timezone' => 'timezone',
    'subaccount_type' => 'subaccountType',
    'email_accepted' => 'emailAccepted',
    'phone_accepted' => 'phoneAccepted',
    'avatar' => 'avatar'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
